// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evvqkjoyquelxkeoaser.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dnFram95cXVlbHhrZW9hc2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTIwMTgsImV4cCI6MjA2MTY2ODAxOH0.Y9RNKe9ex7c-paMwKlYMuEyTGF3Z75OlgBV2pkegKns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);